[package]
name = "quoata-board"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
quoata-core = { path = "../crates/core" }
tauri = { version = "2.11.5", features = ["tray-icon", "image-png", "macos-private-api"] }
tauri-plugin-window-state = "2.4.1"
tauri-plugin-autostart = "2.5.1"
tauri-plugin-global-shortcut = "2.3.2"
tauri-plugin-opener = "2"
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tokio.workspace = true
