[package]
name = "quoata-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
quoata-core = { path = "../core" }
tokio = { workspace = true, features = ["net", "time", "sync", "macros", "rt-multi-thread"] }
chrono.workspace = true
serde_json.workspace = true
