[package]
name = "quota-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
quota-core = { path = "../core" }
tokio = { workspace = true, features = ["net", "time", "sync", "macros", "rt-multi-thread"] }
chrono.workspace = true
serde_json.workspace = true

[dev-dependencies]
wiremock = "0.6.5"
